### ISSUE TITLE
Webpack fails at 'node-sass'

### ISSUE THREAD

**Issue by collinstheuncoder** [keppelen/react-facebook-login#162]
Tried setting up everything as explained but there was a problem encountered when compiling the Sass files.  Tried installing node-sass but for some reason, it fails. 

**Error on npm start**

```
ERROR in Cannot find module 'node-sass'
 @ ./src/facebook.js 19:16-50
webpack: Failed to compile.
```

**Error upon trying to install node-sass**

```
λ npm i node-sass -D

> node-sass@3.13.1 install E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\node-sass

> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\EdX Web Course\\ReactJS\\react-facebook-login\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.1.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (E:\\EdX Web Course\\ReactJS\\react-facebook-login\\node_modules\\which\\which.js:13:12)\n    at F (E:\\EdX Web Course\\ReactJS\\react-facebook-login\\node_modules\\which\\which.js:68:19)\n    at E (E:\\EdX Web Course\\ReactJS\\react-facebook-login\\node_modules\\which\\which.js:80:29)\n    at E:\\EdX Web Course\\ReactJS\\react-facebook-login\\node_modules\\which\\which.js:89:16\n    at E:\\EdX Web Course\\ReactJS\\react-facebook-login\\node_modules\\isexe\\index.js:42:5\n    at E:\\EdX Web Course\\ReactJS\\react-facebook-login\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python c:\users\sleek\appdata\local\enthought\canopy\user\scripts\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: c:\users\sleek\appdata\local\enthought\canopy\user\scripts\python.EXE -c import platform; print(platform.python_version());
gyp ERR! stack ImportError: No module named site
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:270:12)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:897:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:340:11)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at Socket.emit (events.js:210:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:549:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\EdX Web Course\\ReactJS\\react-facebook-login\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\EdX Web Course\ReactJS\react-facebook-login\node_modules\node-sass
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sleek\AppData\Roaming\npm-cache\_logs\2017-07-26T16_33_07_931Z-debug.log
```

**Comment by keppelen** [comment]
you can try `npm rebuild node-sass`?

**Comment by nxmohamad** [comment]
the above solution is worth trying as in a similar situation before it did the trick for me

**Comment by collinstheuncoder** [comment]
Yup! That worked. Thanks!

**Comment by ariefbruce** [comment]
`npm rebuild node-sass` not work for me, I using node v8.9.4

```
$ node -v
v8.9.4

$ npm rebuild node-sass

$ npm start

> react-facebook-login@4.0.0 start E:\react-facebook-login
> cross-env NODE_ENV=development node_modules/.bin/webpack-dev-server --config webpack.config.js

http://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from ./demo
Hash: 3aea5a8e21eb162f889b
Version: webpack 1.12.15
Time: 2677ms
         Asset    Size  Chunks             Chunk Names
demo/bundle.js  346 kB       0  [emitted]  demo
chunk    {0} demo/bundle.js (demo) 289 kB [rendered]
    [0] multi demo 40 bytes {0} [built]
    [1] (webpack)/hot/dev-server.js 1.85 kB {0} [built]
    [2] (webpack)/hot/log-apply-result.js 813 bytes {0} [built]
    [3] ./demo/index.js 5.18 kB {0} [built] [1 error]
    [4] ./~/react/index.js 190 bytes {0} [built]
    [5] ./~/process/browser.js 5.42 kB {0} [built]
    [6] ./~/react/cjs/react.production.min.js 5.41 kB {0} [built]
    [7] ./~/object-assign/index.js 2.11 kB {0} [built]
    [8] ./~/fbjs/lib/emptyObject.js 332 bytes {0} [built]
    [9] ./~/fbjs/lib/emptyFunction.js 959 bytes {0} [built]
   [10] ./~/react/cjs/react.development.js 45.2 kB {0} [built]
   [11] ./~/fbjs/lib/invariant.js 1.51 kB {0} [built]
   [12] ./~/fbjs/lib/warning.js 1.9 kB {0} [built]
   [13] ./~/prop-types/checkPropTypes.js 2.87 kB {0} [built]
   [14] ./~/prop-types/lib/ReactPropTypesSecret.js 314 bytes {0} [built]
   [15] ./~/react-router/lib/index.js 3.62 kB {0} [built]
   [16] ./~/react-router/lib/RouteUtils.js 2.84 kB {0} [built]
   [17] ./~/react-router/lib/PropTypes.js 732 bytes {0} [built]
   [18] ./~/prop-types/index.js 956 bytes {0} [built]
   [19] ./~/prop-types/factoryWithTypeCheckers.js 19.8 kB {0} [built]
   [20] ./~/prop-types/factoryWithThrowingShims.js 1.49 kB {0} [built]
   [21] ./~/react-router/lib/PatternUtils.js 7.81 kB {0} [built]
   [22] ./~/invariant/browser.js 1.52 kB {0} [built]
   [23] ./~/react-router/lib/Router.js 6.13 kB {0} [built]
   [24] ./~/create-react-class/index.js 699 bytes {0} [built]
   [25] ./~/create-react-class/factory.js 28.3 kB {0} [built]
   [26] ./~/react-router/lib/createTransitionManager.js 9.19 kB {0} [built]
   [27] ./~/react-router/lib/routerWarning.js 845 bytes {0} [built]
   [28] ./~/warning/browser.js 1.81 kB {0} [built]
   [29] ./~/react-router/lib/computeChangedRoutes.js 2.22 kB {0} [built]
   [30] ./~/react-router/lib/TransitionUtils.js 4.74 kB {0} [built]
   [31] ./~/react-router/lib/AsyncUtils.js 1.66 kB {0} [built]
   [32] ./~/react-router/lib/isActive.js 4.51 kB {0} [built]
   [33] ./~/react-router/lib/getComponents.js 1.19 kB {0} [built]
   [34] ./~/react-router/lib/PromiseUtils.js 148 bytes {0} [built]
   [35] ./~/react-router/lib/matchRoutes.js 8.38 kB {0} [built]
   [36] ./~/react-router/lib/InternalPropTypes.js 1.05 kB {0} [built]
   [37] ./~/react-router/lib/RouterContext.js 4.4 kB {0} [built]
   [38] ./~/react-router/lib/getRouteParams.js 569 bytes {0} [built]
   [39] ./~/react-router/lib/ContextUtils.js 3.85 kB {0} [built]
   [40] ./~/react-router/lib/RouterUtils.js 896 bytes {0} [built]
   [41] ./~/react-router/lib/Link.js 4.65 kB {0} [built]
   [42] ./~/react-router/lib/IndexLink.js 1.04 kB {0} [built]
   [43] ./~/react-router/lib/withRouter.js 2.69 kB {0} [built]
   [44] ./~/hoist-non-react-statics/index.js 1.39 kB {0} [built]
   [45] ./~/react-router/lib/IndexRedirect.js 1.91 kB {0} [built]
   [46] ./~/react-router/lib/Redirect.js 3.02 kB {0} [built]
   [47] ./~/react-router/lib/IndexRoute.js 1.9 kB {0} [built]
   [48] ./~/react-router/lib/Route.js 1.75 kB {0} [built]
   [49] ./~/react-router/lib/match.js 2.81 kB {0} [built]
   [50] ./~/history/lib/Actions.js 628 bytes {0} [built]
   [51] ./~/react-router/lib/createMemoryHistory.js 1.08 kB {0} [built]
   [52] ./~/history/lib/useQueries.js 4.03 kB {0} [built]
   [53] ./~/query-string/index.js 4.31 kB {0} [built]
   [54] ./~/strict-uri-encode/index.js 182 bytes {0} [built]
   [55] ./~/history/lib/runTransitionHook.js 762 bytes {0} [built]
   [56] ./~/history/lib/LocationUtils.js 3.7 kB {0} [built]
   [57] ./~/history/lib/PathUtils.js 2.97 kB {0} [built]
   [58] ./~/history/lib/useBasename.js 3.64 kB {0} [built]
   [59] ./~/history/lib/createMemoryHistory.js 3.83 kB {0} [built]
   [60] ./~/history/lib/createHistory.js 5.66 kB {0} [built]
   [61] ./~/history/lib/AsyncUtils.js 1.13 kB {0} [built]
   [62] ./~/react-router/lib/useRouterHistory.js 635 bytes {0} [built]
   [63] ./~/react-router/lib/applyRouterMiddleware.js 2.3 kB {0} [built]
   [64] ./~/react-router/lib/browserHistory.js 550 bytes {0} [built]
   [65] ./~/history/lib/createBrowserHistory.js 3.38 kB {0} [built]
   [66] ./~/history/lib/ExecutionEnvironment.js 164 bytes {0} [built]
   [67] ./~/history/lib/BrowserProtocol.js 3.19 kB {0} [built]
   [68] ./~/history/lib/DOMUtils.js 2.19 kB {0} [built]
   [69] ./~/history/lib/DOMStateStorage.js 2.55 kB {0} [built]
   [70] ./~/history/lib/RefreshProtocol.js 1.13 kB {0} [built]
   [71] ./~/react-router/lib/createRouterHistory.js 611 bytes {0} [built]
   [72] ./~/react-router/lib/hashHistory.js 535 bytes {0} [built]
   [73] ./~/history/lib/createHashHistory.js 4.76 kB {0} [built]
   [74] ./~/history/lib/HashProtocol.js 4.23 kB {0} [built]
   [75] ./src/facebook.js 9.69 kB {0} [built]
   [76] ./src/objectToParams.js 432 bytes {0} [built]
   [77] ./src/facebook-with-button.js 6.16 kB {0} [built] [1 error]

ERROR in ./demo/index.js
Module not found: Error: Cannot resolve module 'react-dom' in E:\react-facebook-login\demo
 @ ./demo/index.js 9:16-36

ERROR in Cannot find module 'node-sass'
 @ ./src/facebook-with-button.js 19:16-50
webpack: Failed to compile.
```
