### ISSUE TITLE
Error while trying to mount component in tests

### ISSUE THREAD

**Issue by bytheway875** [keppelen/react-facebook-login#217]
When I attempt to mount a component that contains the FacebookLogin component in my Jest tests, I get the following error:

```
TypeError: Cannot read property 'parentNode' of undefined
```

with this backtrace pointing to the react-facebook-login package:

```
 at node_modules/react-facebook-login/dist/facebook-login-render-props.js:1:4621
      at t.value (node_modules/react-facebook-login/dist/facebook-login-render-props.js:1:4652)
      at t.value (node_modules/react-facebook-login/dist/facebook-login-render-props.js:1:3509)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:8770:24)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:9946:9)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:542:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:581:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:438:27)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:10050:9)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:11017:42)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:10967:7)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:10878:7)
      at scheduleWorkImpl (node_modules/react-dom/cjs/react-dom.development.js:10732:11)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:10689:12)
      at scheduleTopLevelUpdate (node_modules/react-dom/cjs/react-dom.development.js:11193:5)
      at Object.updateContainer (node_modules/react-dom/cjs/react-dom.development.js:11231:7)
      at node_modules/react-dom/cjs/react-dom.development.js:15226:19
      at Object.unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:11102:12)
      at renderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:15225:17)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:15290:12)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:218:50)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:98:16)
      at mount (node_modules/enzyme/build/mount.js:19:10)
```

**Comment by mciastek** [comment]
@bytheway875 if you are using Jest, you can put dummy `<script>` element in `document.body`, before you run tests. So for example:

browser-mocks.js
```js
const fbScript = document.createElement('script');
fbScript.id = 'facebook-jssdk';

document.body.appendChild(fbScript);
```

package.json (or any file with Jest config):
```json
"jest": {
  "setupFiles": [
    "<rootDir>/testing/browser-mocks.js"
   ],
}
```

You need to do it to avoid run the rest of the code here: https://github.com/keppelen/react-facebook-login/blob/04cf981b7cb3b9020aa86f9a9f723b76041966f1/src/facebook.js#L67

I think in the future @keppelen it needs to be changed, in order to use this library in tests.

**Comment by wowczarczyk** [comment]
For those using CRA, put the content of the `browser-mocks.js` above into `src/setupTests.js` (or `src/setupTests.ts` if using typescript)
