### ISSUE TITLE
Server Side Rendering issue

### ISSUE THREAD

**Issue by liviuignat** [keppelen/react-facebook-login#92]
Hi, by `document` on `componentWillMount`, will throw an error when using in a NodeJS environment, together with SSR.

Client specific code, like `document`, `window`, etc, should only be used in `componentDidMount`

Cheers,

**Comment by keppelen** [comment]
My ideia this componente functionaly only client side, not run em SSR.

**Comment by janicklas-ralph** [comment]
Is there any specific reason you don't want this to be rendered on the server?

If not, it must be a relatively easy change to get this fixed.

**Comment by greyvugrin** [comment]
@keppelen disabling this from being included in ssr can be tricky, if the markup presented by the client is different than that of the server, react has to re-render the entire app, and you lose the benefits of SSR.

That error would look something like:

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) .$name"><label for="2111e75b-23e5-484e-9
 (server) .$name"><label for="3de2ba9c-0384-405b-b

I've submitted a PR ( #93 ) that addresses this issue by moving the error causing code into componentDidMount. It solved the issue in my project.

**Comment by isaachinman** [comment]
I commented on the PR itself as well, but I would really like to see this merged if whoever maintains this repo doesn't see any obvious problems with it. It's now 2017 and statements like "not run em SSR" really aren't appropriate for React components that get hundreds of downloads daily via npm.

**Comment by greyvugrin** [comment]
I believe @keppelen does, haven't seen any activity on the pr so far unfortunately. If this is pressing you're welcome to install the package using my fork via the github url:

```
"react-facebook-login": "github:greyvugrin/react-facebook-login"
```

**Comment by isaachinman** [comment]
Yup, I'm aware of that workaround but I'd rather not start depending on forks unless it's certain the maintainer has abandoned the project or refuses to support SSR. Cheers for your contribution!

**Comment by greyvugrin** [comment]
Understood. And my pleasure!

**Comment by greyvugrin** [comment]
@isaachinman Looks like it has been merged!

**Comment by greyvugrin** [comment]
@liviuignat the pr fixing this has been merged, give the new version a shot and comment back if the issue is solved.

**Comment by isaachinman** [comment]
Actually, it looks like this now throws a critical error:

    ReferenceError: window is not defined
    [1]     at Object.e.__esModule.default (/node_modules/react-facebook-login/dist/facebook-login.js:1:5613)

(Hopefully) without getting too far into the codebase here, I'd assume window is being referenced somewhere in a portion of the lifecycle which can/will be executed server side.

**Comment by felipegcampos** [comment]
I came across the same problem today and even deleting and installing node modules again it still pulling the version containing 'componentWillMount' . Is that right ?

**Comment by greyvugrin** [comment]
@isaachinman just noticed that a reference to window is being made with default props, I may not have had that issue on my end because I passed the props explicitly.

```
static defaultProps = {
    textButton: 'Login with Facebook',
    typeButton: 'button',
    redirectUri: window.location.href,
```

This is just a hypothesis though. Can you paste over any more error info?

**Comment by greyvugrin** [comment]
@felipegcampos sometimes npm takes a bit to get the latest version. Try doing `npm view react-facebook-login`, and ensure the current version (listed in the package.json of the repo) is there. Also you might have been trying before the PR was merged? It was approved not too long ago

**Comment by isaachinman** [comment]
I can take a further look tomorrow and provide whatever's needed, even a PR if necessary. I'd like to get this sorted for an ongoing project. Npm probably does have some sort of cache/TTL, but I definitely tested it _after_ the merge.

**Comment by felipegcampos** [comment]
Thanks @greyvugrin , I will check. Meanwhile, my workaround is to work with the 3.4.1 version which has no such line:

`static defaultProps = {
    textButton: 'Login with Facebook',
    typeButton: 'button',
    scope: 'public_profile,email',
    xfbml: false,
    cookie: false,
    reAuthenticate: false,
    size: 'metro',
    fields: 'name',
    cssClass: 'kep-login-facebook',
    version: '2.3',
    language: 'en_US',
  };`

@isaachinman in case you need it working for isomorphic applications as I do ..... it can be the fastest solution.

**Comment by greyvugrin** [comment]
@isaachinman sounds good, I think adding the prop for redirect explicitly will solve your problem for now, lmk. In your case the new error means that you have the newer version

**Comment by greyvugrin** [comment]
@felipegcampos gotcha, that version wouldn't include code that fixes the other issue though (componentWillMount -> DidMount)

**Comment by felipegcampos** [comment]
@greyvugrin that's right. It was my mistake. Actually, it works for me because I'm not rendering the component at first. Thus, it fixes my problem just removing the window's reference from the static declaration.

**Comment by isaachinman** [comment]
@greyvugrin Yup, it was the defaultProp for `redirectUri` that was referencing `window` and causing things to break. I'll submit a quick PR to fix this, hopefully @keppelen merges it quickly, and we'll have full SSR support.

**Comment by smk1992** [comment]
Hi I don't, think this is fixed yet:
`ReferenceError: window is not defined
    at Object.e.__esModule.default (/Users/salman/dev/projects/devBBQ/lifeforce/lifeforce-web/node_modules/react-facebook-login/dist/facebook-login.js:1:5613)`
